### ISSUE TITLE
Text misaligned with \twocolumn iin single-col document

### ISSUE THREAD

**Issue by urrameu** [PhelypeOleinik/lipsum#4] opened 2021-04-27 00:51 UTC
Hi,

Using `\twocolumn` in a single-column document completely messes up the text alignment of subsequent `lipsum` text. A MWE:

```latex
\documentclass{article}
\usepackage{lipsum}

\begin{document}
\twocolumn
\lipsum
\end{document}
```

I tried (1) adding some manual text before `\lipsum`, (2) `\twocolumn[blah]`, (3) the `nopar` option, (4) `\unpacklipsum` + `\lipsumexp`, and (5) messing with `\SetLipsumParListItemStart` & friends; the problem always persists. Very weird!

[lipsum-twocolumn-bug.pdf](https://github.com/PhelypeOleinik/lipsum/files/6381138/lipsum-twocolumn-bug.pdf)

**Comment by PhelypeOleinik** [comment] 2021-04-27 01:06
Misalignment?  Are you talking about the bad line breaks, like these:

> ![path867](https://user-images.githubusercontent.com/12678598/116169285-c863d800-a6da-11eb-8637-247affb47350.png)

If so, then this is a duplicate of #2, which for mortal men means “Add an option to use Latin hyphenation patterns”.  Something like `\usepackage[latin]{babel}` or, if you don't want your entire document in Latin:
```latex
\documentclass{article}
\usepackage{babel} % load babel with other languages here
\usepackage{lipsum}
\begin{document}
\twocolumn
\begin{otherlanguage}{latin}
\lipsum
\end{otherlanguage}
\end{document}
```

**Comment by urrameu** [comment] 2021-04-27 01:54
Yes, the problem is the bad linebreaks, but they are not caused by the lack of hyphenation patterns: this problem does not occur if you use the `twocolumn` class option.

A slightly modified MWE:

```latex
\documentclass
%[twocolumn]
{article}
\usepackage[left=160pt,right=160pt]{geometry}
\usepackage{lipsum}

\begin{document}
\twocolumn
\lipsum[1-3]
\end{document}
```

If you disable the `\twocolumn` and enable the `[twocolumn]` line, you *should* get the same document, but that is not the case. With the class option, there is some bad spacing, but the text is perfectly justified and nothing from the left column overlaps the right.

The attached pdf includes both versions.
[lipsum-twocolumn-bug-bad-and-good.pdf](https://github.com/PhelypeOleinik/lipsum/files/6381354/lipsum-twocolumn-bug-bad-and-good.pdf)

**Comment by u-fischer** [comment] 2021-04-27 07:08
the `twocolumn` class options activates beside `\twocolumn` also `\sloppy`, and this changes the line breaking. That's not related to the lipsum package.

**Comment by PhelypeOleinik** [comment] 2021-04-27 13:46
@urrameu The `twocolumn` option is not exactly equivalent to the `\twocolumn` command.  Your example makes them look much more alike because you force the margins by using `geometry`, but the option `twocolumn` does a lot more than just split the text area into two columns (which is more or less what the command `\twocolumn` does).  As Ulrike said, the option `twocolumn` does also `\sloppy`, so adding `\sloppy` to the `\twocolumn` version or adding `\fussy` to the `twocolumn` (option) version makes both have the same output.

Regardless, this is unrelated to `lipsum` because you can get the same line breaks by writing the Lorem Ipsum text directly into the document (or with any other text).

**Closed as completed by PhelypeOleinik** 2021-04-27 13:46 UTC
