### ISSUE TITLE
! Package lipsum Error: Language 'latin' undefined.

### ISSUE THREAD

**Issue by cderv** [PhelypeOleinik/lipsum#8] opened 2021-07-27 09:25 UTC
Hi, 

With an updated TeX Live installation, I got issue with this package now 

````
! Package lipsum Error: Language 'latin' undefined.
````

This happens  with a simple file and pdftex engine.

````latex
\documentclass{article}
\usepackage{lipsum}
\begin{document}
\lipsum[1]
\end{document}
````

If I deactivate the auto lang it is working fine 

````latex
\documentclass{article}
\usepackage{lipsum}
\begin{document}
\setlipsum{auto-lang=false}
\lipsum[1]
\end{document}
````

Is there anything else to install to make the package work again with default ? 

I am on windows 10 and tlmgr revision 59291 (2021-05-21 05:14:40 +0200)

Thanks.

**Comment by PhelypeOleinik** [comment] 2021-07-27 11:52
This is partially a duplicate of #6. Oddly though, you said you get the error with pdfTeX (for me it works)... Maybe you don't have all required languages installed: is your installation full or is it a smaller scheme?

Please try loading `babel`, see if it works:
```latex
\documentclass{article}
\usepackage{lipsum}
\usepackage{babel}
\begin{document}
\lipsum[1]
\end{document}
```

P.S.: I didn't mean to close the issue. Stupid finger touched the wrong place on the tiny mobile screen :)

**Comment by cderv** [comment] 2021-07-27 14:13
This is not a full install for sure. 

When I add babel I got this message 

````
! Package babel Error: You haven't defined the language 'latin' yet.
(babel)                Perhaps you misspelled it or your installation
(babel)                is not complete.

See the babel package documentation for explanation.
````

What is missing exactly ? 

This is the first time I get this type of error with this smaller scheme installation. Usually, missing package is in the log and can be easily installed.

**Comment by PhelypeOleinik** [comment] 2021-07-27 18:57
With the last update I made `\lipsum` use proper Latin hyphenation patterns for the dummy text, so you get better line-breaking (see #2).  Though I assumed a full installation with the Latin language installed.  I should add proper recovery when the languages are not available.

> What is missing exactly ?

From `lipsum`, a proper recovery for missing languages (or a dependency listing for `tlmgr` so it installs automatically).  I will correct this for the next update.

From your installation, the Latin hyphenation patterns. I believe it is the [`babel-latin`](https://ctan.org/pkg/babel-latin) package, but maybe [`lahyph`](https://ctan.org/pkg/lahyph) too; I'm not sure (can't check at the moment).

Of course for now you can disable this feature as you showed with `\setlipsum{auto-lang=false}`.

> This is the first time I get this type of error with this smaller scheme installation. Usually, missing package is in the log and can be easily installed.

The missing package is not a package in the LaTeX/`\usepackage` sense, but a CTAN package for Latin hyphenation patterns which are built into the LaTeX format, so you don't see an error about a missing package in the log.

**Comment by cderv** [comment] 2021-07-27 20:47
Thanks that makes sense! 

For now I have indeed deactivated.

**Closed as completed** 2021-07-28 03:22 UTC
Labels: enhancement

**Comment by cderv** [comment] 2021-07-28 07:31
Thanks!
